from ..http.async_http import AsyncHTTPClient


class OrderService:
    def __init__(self, http_client: AsyncHTTPClient):
        self._http = http_client

    async def get_orders(self): ...

    async def post_orders(self): ...

    async def patch_orders(self): ...

    async def get_orders_uuid(self): ...

    async def delete_orders_uuid(self): ...

    async def get_orders_orderuuid_intakes(self): ...

    async def post_orders_uuid_refusal(self): ...

    async def post_orders_uuid_clientreturn(self): ...
