from ..http.async_http import AsyncHTTPClient


class PrintService:
    def __init__(self, http_client: AsyncHTTPClient):
        self._http = http_client

    async def post_print_orders(self): ...

    async def get_print_orders_uuid(self): ...

    async def get_print_orders_uuidpdf(self): ...

    async def post_print_barcodes(self): ...

    async def get_print_barcodes_uuid(self): ...

    async def get_print_barcodes_uuidpdf(self): ...
